version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: flashcards-database
    environment:
      POSTGRES_USER: flashcards_database_user
      POSTGRES_PASSWORD: QbEWo9JeRx3qDkkcQZnLwvO7IHQdhbI4
      POSTGRES_DB: flashcards_database
    ports:
      - "5432:5432"
